name: CI
on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 10.x, 12.x, 13.x, 14.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
          ${{ runner.os }}-

    - run: npm install

    - run: npm test
